[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version = "5.11.0" }
assertj-core = { module = "org.assertj:assertj-core", version = "3.26.3" }
fastdoubleparser = { module = "ch.randelshofer:fastdoubleparser", version = "1.0.0" }
gummy-bears = { module = "com.toasttab.android:gummy-bears-api-33", version = "0.9.0" }
spotbugs = { module = "com.github.spotbugs.snom:spotbugs-gradle-plugin", version = "6.0.20" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version = "2.18.1" }

[plugins]
jmh = { id = "me.champeau.jmh", version = "0.7.2" }
pitest = { id = "info.solidsoft.pitest", version = "1.15.0" }
animalsniffer = { id = "ru.vyarus.animalsniffer", version = "1.7.1" }
bnd = { id = "biz.aQute.bnd.builder", version = "7.0.0" }
